#!/bin/bash
#PBS -P TB_NN_INFOTHEORY
#PBS -q dtq
#PBS -l select=1:ncpus=1:mem=8GB
#PBS -l walltime=03:00:00

PROJECT=TB_NN_INFOTHEORY

PROJECT_LOC=/project/TB_NN_INFOTHEORY/rmck6484_thesis

module load python/3.9.15 hdf5/1.10.6 
cd "$PBS_O_WORKDIR"
python --version
virtualenv --system-site-packages ${PROJECT_LOC}/pyenv/
source ${PROJECT_LOC}/pyenv/bin/activate
cd ${PROJECT_LOC}


python3 ${PROJECT_LOC}/src/gather_data_h5.py ${FOLDER}
