#!/bin/bash
#PBS -P TB_NN_INFOTHEORY
#PBS -l select=1:ncpus=1:mem=1GB
#PBS -l walltime=00:05:00

PROJECT=TB_NN_INFOTHEORY

PROJECT_LOC=/project/TB_NN_INFOTHEORY/rmck6484_thesis

module load hdf5/1.8.14 
module load python/3.7.7
cd "$PBS_O_WORKDIR"
python --version
virtualenv --system-site-packages ${PROJECT_LOC}/pyenv/
source ${PROJECT_LOC}/pyenv/bin/activate
pip install -r ${PROJECT_LOC}/requirements.txt
cd ${PROJECT_LOC}
